### ISSUE TITLE
Describing a response

### ISSUE THREAD

**Issue by whoisstan** [Apipie/apipie-rails#273]
So i have a regular 'index' method which responds with a list of items. How would I describe the response format? Can't seem to find it.

**Comment by saneshark** [comment]
I'd be open to working on this. I've used JSON-Schema specs in the past which is great because it allows you to also identify attributes that are for example of type String, but could also potentially be null. As a ruby developer we often overlook the value of type handling and I can't think of a better way to define it other than to have some equivalent of request/view specs that compare the response.body to against such a schema. It would be very nice if the example generators could include comments in the JSON perhaps that are based on such a schema spec.

**Comment by jonricaurte** [comment]
@saneshark apipie does support nils. You can use allow_nil: true which can be found here:

https://github.com/Apipie/apipie-rails

**Comment by jeremywadsack** [comment]
:+1: 

An issue with using the `examples` command is that it "will be formatted as code." More specifically, it seems to format as JSON (or something). So when I have `formats ['csv']` it color codes things that shouldn't be colored. Even for JSON response, if my `example` block includes more than just the returned value the formatter tries to make all of that into code. So I have to use `# comments` to add notes to the example.

Would be great to see this enhanced. What about just letting the author use marked-up content for the `examples`, rather than trying to do something fancy (that may not make sense for all cases)?

**Comment by cgagon** [comment]
Are there any plans to undertake this feature?  RAML and Swagger both support this so I think it would be a great addition to the DSL.

**Comment by santiph** [comment]
+1

**Comment by elasti-ron** [comment]
See #588 for a discussion on a possible approach for addressing this topic.

**Comment by sordina** [comment]
This is especially critical given that the Swagger-Codegen community seem have a policy of making generated code return nil for API requests if the response isn't documented...

https://github.com/swagger-api/swagger-codegen/issues/6388#issuecomment-326991057

**Comment by iNecas** [comment]
@sordina please have a look at https://github.com/Apipie/apipie-rails/pull/588 - the implementation is pretty close, any early feedback can help us moving this feature forward.

**Comment by iNecas** [comment]
Fixed by https://github.com/Apipie/apipie-rails/pull/588
