### ISSUE TITLE
Extension points for parameters

### ISSUE THREAD

**Issue by iNecas** [Apipie/apipie-rails#330]
We have a Rails app with highly-plugable architecture, where it's possible to add model attributes to from an external engine. So let's say the host app has something like this (putting the strong params aside):

``` ruby
param :person, Hash do
  param :name, String
end
def create
  User.create(params[:person])
end
```

I could have something like this in a plugin code:

``` ruby
def_param_group :person_extension, Hash, :extend => apipie_action(PeopleController, :create, :person) do
  param :email, String
end
```

The `:extend` keyword would mean that this param group should be included when the body of the person param is being evaluated. Similarly, to extend some param group, one would go:

``` ruby
def_param_group :person_extension, Hash, :extend => apipie_param_group(PeopleController, :person_group, :person) do
  param :email, String
end
```

**Comment by stbenjam** [comment]
I guess the biggest thing here is I want to be able to add extensions in the context of the controller to make it easier for plugins doing alias_method_chain. I think both of the examples you showed, the block would be executed inside the Apipie DSL.

In the example I had constructed in Foreman (https://github.com/stbenjam/foreman/commit/ffc9009a99aa63e2b402ae5f7e8c95f61c7effb5), I had to call the models individually in each param group (`Hostgroup.extended_attributes...`) because I couldn't use controller methods like `resource_class`.

So specifically in the plugin case, I'd like to have it all bundled up in some concern I could just include in the various controllers, that would extend `"#{resource_class.to.s.whatever}_group"` with `resource_class.extended_parameters`

I'm not sure if that's useful to anyone but Foreman.

**Comment by shlomizadok** [comment]
@iNecas @stbenjam - This issue pops up again ( [Foreman #16490](http://projects.theforeman.org/issues/16490)) , would love to try and promote it

**Comment by ares** [comment]
And another one [Foreman #17678](http://projects.theforeman.org/issues/17678)

**Comment by iNecas** [comment]
Due to the way the param groups are implemented, it was not possible/easy to allow extending on that level (as we can't never be sure, if the param group was already included somewhere). However, extending on per action basis should work for most cases. See https://github.com/Apipie/apipie-rails/pull/554 for the implementation.

**Comment by iNecas** [comment]
Fixed via https://github.com/Apipie/apipie-rails/pull/554
