### ISSUE TITLE
Hash validator fails with encoded JSON value

### ISSUE THREAD

**Issue by wordofchristian** [Apipie/apipie-rails#374]
I have an endpoint that has Hash as one of it's parameters.

 ```ruby
param :thing_form, Hash, 'Thing form values', required: true do
    param :name, String, "Thing's name"
    param :color, String, "Thing's color"
end
```

The problem is that when the client posts data it does it as a JSON string in the request body. Rails automatically knows how to convert this JSON string into a Hash when retrieving the value of `params[:thing_form]`. 

Apipie however is failing with invalid type error.
`Invalid parameter 'thing_form' value "{\"name\":\"Foo\",\"color\":\"red\"}": Must be Hash`

Should I just be using an `:undef` validator for the form, or should apipie try to parse the JSON before performing Hash type validation?

What does everyone else do for cases like this?

**Comment by Pajk** [comment]
@wordofchristian Hello, I know it's few months since you asked this question but if you didn't resolve it I could have a solution for you. You can create your own custom validator which would actually very simple because it's only purpose would be to parse the json to a ruby Hash and pass this it to HashValidator.

See:
https://github.com/Apipie/apipie-rails#adding-custom-validator
https://github.com/Apipie/apipie-rails/blob/master/lib/apipie/validator.rb#L273

**Comment by vkeziah** [comment]
I too have the same issue with rails5, Can any one give me fix for this

**Comment by BrahimDa** [comment]
+1

**Comment by thiensubs** [comment]
+1 I has the same issue with Rails 5.0.0.1
