### ISSUE TITLE
Support for multiple actions on the same method

### ISSUE THREAD

**Issue by vassyz** [Apipie/apipie-rails#381]
My current setup is as follows:

routes.rb:

     match 'banners/:id/preview' => 'banners#preview', as: :banner_preview, via: [:get, :post]

banners_controller.rb:

     api :GET, 'banners/:id/preview'
     api :POST, 'banners/:id/preview'
     param :id, Integer
     param :field_name, String

This doesn't really work properly, the calls sort of get merged into the documentation page.

**Comment by joshpfosi** [comment]
I am currently experiencing a similar issue. How do I differentiate documentation by action for the same method?

**Comment by Pajk** [comment]
@vassyz @joshpfosi This is by design and won't be changed.

If I understand it correctly you have one controller method which does two different things based on how it's accessed (get vs post) and you expect different parameters and want to have them document separately, right?

The solution here is to use two different methods so the documentation can be completely different.
So you end up with routes being similar to eg:

    get 'banners/:id/preview' => 'banners#get_preview'
    post 'banners/:id/preview' => 'banners#create_preview'

I think it's cleaner way how to do it no matter if you are using apipie or not.

**Comment by andrewls** [comment]
In most cases, I would agree with you, but there are always exceptions to the rule, and it would be nice to have the flexibility to actually do what makes the code most readable in those situations, instead of being forced to change how my code is written to accommodate the documentation tool I'm using. 

I have two methods, a post and a get, that do entirely the same thing, except that the post needs to run two lines of code in the middle that the get does not. Now granted, I can just factor out the common pieces into two method calls, and then have two methods that call those separate methods with the post performing its internal logic in between. But it looks a lot cleaner and more readable to have them combined into one method with a simple if statement in the middle. Because of the fact that Apipie doesn't support multiple actions using the same method, I have to write them as separate methods that essentially do the same thing, with one minor difference. It's not a common need, but legitimate use cases for this do come up, and it wouldn't be a bad idea to support it.
