### ISSUE TITLE
Including Devise API docs

### ISSUE THREAD

**Issue by jetienne** [Apipie/apipie-rails#463]
Hi,

I am using https://github.com/lynndylanhurley/devise_token_auth#configuration-cont as auth tool, and I would like to include these endpoints into my documentation. Any idea on how I could do that?

Best,

**Comment by chaomao** [comment]
hi
I use this gem also, I just override default controller with customized controller, then call super to make sure didn't change anything in devise. Then give api spec, I think that's the only way to have apipie works.

```ruby
class Staff::SessionsController < DeviseTokenAuth::SessionsController
  resource_description { resource_id "sessions" }

  api :POST, "/staff_auth/sign_in", "sign in"
  description 'sign in'
  param :email, String, required: true
  param :password, String, required: true
  example <<-DATA
{
  "data": {
    "id": 1,
    "email": "admin@admin.com",
    "provider": "email",
    "category": "admin",
    "uid": "admin@admin.com",
    "nickname": null,
    "image": null,
    "cellphone": null,
    "name": null,
    "avatar": null,
    "gender": null
  }
}
DATA
  def create
    super 
  end

```

**Comment by iNecas** [comment]
Hi,

I plan to spend more time on Apipie next week with trying to add an ability
to extend the docs without need of
defining the method. I will write here the updates on this once something
ready.

**Comment by stratigos** [comment]
@iNecas any progress on this? Id love to adapt this to `devise_token_auth` as well, and would love a solution beyond "override & call super". Id like to modify apipie so that it can apply a configured set of documentation instructions to any controller name, specifically for one inside a gem, but am not sure where to start. If I can help contribute, I am all ears :smile:.
