### ISSUE TITLE
Is Apipie still maintained?

### ISSUE THREAD

**Issue by jeffbax** [Apipie/apipie-rails#734]
Hi, not meaning for this to come across as unappreciative -- but is it possible to have an update on whether this project is still on-going? The pulse is quite low, with the last release quite some time ago.

There seem to be a lot of open issues without much commentary; and pull requests old & new with seemingly quality fixes (like #716 and #732) that don't get a lot of traction. Hoping things are not dead, or wondering whether there would be interest in adding more maintainers if it is hard to keep up with?

Thanks! ❤️

**Comment by ofedoren** [comment]
Hi, that's OK to ask and sorry for not paying much attention as it was before. Currently it's up to one person (me) whether to add things or not, release stuff or not. Due to the fact that I'm not actually the author of this project and my knowledge is still limited (I don't have much time to spend here reviewing big/complex PRs) I fix or add things that are required by [Foreman](https://github.com/theforeman/foreman) only. So it's kinda maintained.

Regarding a new/more maintainers: well, that's an open question I don't' have answer for, for now. Instead I was thinking about leaving this project as stable as it could be (again, since I'm not quite sure if I would have time to fix things if they break fast enough), merging and releasing from time to time. But, in addition to this, I was thinking about creating a new branch (let's say experimental) with a different versioning where we could easily merge stuff, break things, and do releases more often so it's more "alive" and if a feature/fix was tested enough, CP it into the stable (current) branch with a release.

I'd happy to hear your (or the more people will react, the better) opinion on my suggestion.

**Comment by jeffbax** [comment]
Yeah, I understand not wanting to have a lot stability shifting if there's not a lot of time for oversight. Sometimes projects are better off a little slower :)

I think we'd be interested in an experimental branch that was a little more rapid, or maybe we could have a little more momentum behind with other's contributions (and probably willing to help out in the oversight part). We currently use this project for generating our documentation and the param parsing (though, we have recently run into some bugs there we are trying to put in fixes for -- thus this question)

We are probably in a similar boat of maybe not a ton of time to build out rapid new functionality, but could spare some cycles for people who are trying to contribute code and fixes themselves (and maybe get through some of the backlog)

**Comment by themilkman** [comment]
I'd also be interested in having an experimental branch. This would at least be a good base for small new PRs (like mine). It'd also be great to get some alpha releases on rubygems of it but this would of course result in a bit more work.

But I'd appreciate any effort to keep Apipie as alive as possible.

**Comment by mathieujobin** [comment]
I think we can close this
