### ISSUE TITLE
Swagger generation mixes up controllers with same name:

### ISSUE THREAD

**Issue by davidwessman** [Apipie/apipie-rails#889]
app/controllers/api/v1/pets_controller.rb
```ruby
module Api
  module V1
    class PetsController < ApiController
      resource_description do
        tags(["Pets"])
      end
    end
  end
end
```

app/controllers/api/v1/owners/pets_controller.rb
```ruby
module Api
  module V1
    module Owners
      class PetsController < ApiController
        resource_description do
          tags(["Owners"])
        end
      end
    end
  end
end
```

With these two controllers, the tags in swagger-output will be set to `Owners` for both `PetsControllers`.
(It could probably be set to `Pets` as well if it is something based on alphabetical sorting, but not the two separate tags)

Is there some matching done only on the class name? It needs to consider nested modules.

**Comment by PanosCodes** [comment]
I looked into it a bit, the missing tag never ends up in the Swagger generator.

It should be present in [Apipie::MethodDescription::tag_list ](https://github.com/PanosCodes/apipie-rails/blob/a403e2e491c3ba7d29c949ab2d6dec14e8158cf8/lib/apipie/method_description.rb#L80-L87) but I think it's not 🤔

**Comment by davidwessman** [comment]
Fixed it by adding the `namespaced_resources: true`, should this be the default in a future major version?

**Comment by epugh** [comment]
I ran into this issue and hunted around for a while till I found this ticket.  Feels like since namespacing is common in Rails app, that this should default to true... ;-).

My first cut of adding some `api!` didn't go well because I have two BooksController, until I found this parameter.

![image](https://github.com/Apipie/apipie-rails/assets/22395/d18665b0-de56-4f3d-8285-951f01cf8e01)
